### ISSUE TITLE
Interface timeout / hangs on *RST for Rigol DP832

### ISSUE THREAD

**Issue by jamasi** [python-ivi/python-vxi11#27]
Trying this simple sequence of commands sometimes hangs the LAN interface of the Rigol DP832(A) with firmware version 00.01.14.00.03 and resets the connection:

```python
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import vxi11
>>> inst = vxi11.Instrument("192.168.1.15")
>>> inst.ask("*IDN?")
u'RIGOL TECHNOLOGIES,DP832,DP8C194205678,00.01.14'
>>> inst.ask("*RST")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/vxi11/vxi11.py", line 743, in ask
    return self.read(num, encoding)
  File "/usr/lib/python2.7/dist-packages/vxi11/vxi11.py", line 731, in read
    return self.read_raw(num).decode(encoding).rstrip('\r\n')
  File "/usr/lib/python2.7/dist-packages/vxi11/vxi11.py", line 701, in read_raw
    raise Vxi11Exception(error, 'read')
vxi11.vxi11.Vxi11Exception: 15: IO timeout [read]
>>>
```
```
$ cat /usr/lib/python2.7/dist-packages/vxi11/version.py
__version__ = '0.9'
```

Sometimes the connection seems to be only half closed so that further commands or a reconnection to the device fails until the DP832 is power-cycled. In this state the web interface does not work as well.

Doing the same directly via ```telnet 192.168.1.15 5555``` does not cause any problems.

**Comment by alexforencich** [comment]
And here I was thinking Rigol only screwed up their USBTMC implementation on basically all of their devices.  This is likely a firmware bug, but I don't have access to one of those supplies so there's not much I can do about it.  If you can send me a pcap file, I'll take a look at it, but the answer will probably end up being "don't use *RST on DP832 with firmware version XYZ."

**Comment by kratsg** [comment]
I've hit something similar with a DP821A. I find that after about 15 minutes of doing nothing (after opening a connection) - it stops responding and a reboot of the power supply is all that I can do to make it work.

If you give me instructions to provide debugging information, i can add it.
