### ISSUE TITLE
Rigol DM3068 workaround Device locked by another link [write]

### ISSUE THREAD

**Issue by ornotermes** [python-ivi/python-vxi11#5]
Hello,

Got a new DM3068 yesterday and have been trying to connect to it without success. After a lot of searching it turns out that it require the lock_timeout to be set to 0 ( http://optics.eee.nottingham.ac.uk/vxi11/ ). Could be a useful example, it would have saved me hours.

>>> import vxi11
>>> instr = vxi11.Instrument("192.168.1.171")
>>> print(instr.ask("*IDN?"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "vxi11/vxi11.py", line 495, in ask
  File "vxi11/vxi11.py", line 480, in write
  File "vxi11/vxi11.py", line 423, in write_raw
vxi11.vxi11.Vxi11Exception: 11: Device locked by another link [write]
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 67, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
OSError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "vxi11/vxi11.py", line 495, in ask
  File "vxi11/vxi11.py", line 480, in write
  File "vxi11/vxi11.py", line 423, in write_raw
vxi11.vxi11.Vxi11Exception: 11: Device locked by another link [write]
>>> instr.lock_timeout = 0
>>> print(instr.ask("*IDN?"))
Rigol Technologies,DM3068,DM3O*********,01.01.00.01.08.00
>>>

**Comment by alexforencich** [comment]
Very interesting.  It would be possible to add this to the IVI driver for the multimeter, if someone chooses to write one, so this is done automatically when the link is opened.

**Comment by ornotermes** [comment]
Yes, the networking seems a bit quirky overall. But anyway, I'm thinking of writing a driver. Still, it might save someone some frustration to put up the info (I didn't even look at ivi before getting communications working). And who knows, there might be more untested gear out there needing the same workaround.

**Comment by alexforencich** [comment]
Take a look at the default SCPI driver that's used as a base for the Agilent DMM.  It might cover a lot of the basic functionality, presuming the Rigol unit is more or less SCPI compliant.  

And yes, it's a very safe bet that there are LOTS of other instruments with screwy remote interfaces.

**Comment by zikako74** [comment]
http://optics.eee.nottingham.ac.uk/vxi11/

Rigol DM3068 multimeters
In vxi11_user.cc you need to change the write_parms.lock_timeout value to 0, rather than VXI11_DEFAULT_TIMEOUT, in the vxi11_send() function (currently line 466 in version 1.10). If you don't do this, the DM3068 returns 'Device Locked'. Thanks to Ian West for reporting this gotcha.

**Comment by zikako74** [comment]
this is a solution ?

**Comment by DwaineGarden** [comment]
Working fine for me now... 

Rigol Technologies,DM3068,DM3O163450491,01.01.00.01.10.00
>>>

**Comment by mrechte** [comment]
Another locking problem with DM3068 (also experimented on DG1032) is lock() which seems to be ignored by the instrument (RIGOL always respond with code 0 to device_lock function): several clients may connect to the same equipment and lock the device !

On the other hand DG1032 does not exhibit this OP's problem
